{
 "title": "dataplane",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Pipeline-Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reduction - Input vs. ES-Output",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Input",
     "dimensions": {
      "component_id": "input_tppp",
      "component_kind": "source",
      "component_name": "*",
      "component_type": "fluent",
      "host": "*",
      "pid": "*"
     },
     "metricName": "component_received_events_total",
     "metricQueryType": 1,
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "tppp_v1", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        {
         "name": "component_received_events_total",
         "type": "functionParameter"
        }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "input_tppp" }, "property": { "name": "component_id", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "source" }, "property": { "name": "component_kind", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(component_received_events_total) FROM tppp_v1 WHERE component_id = 'input_tppp' AND component_kind = 'source'",
     "statistic": "Sum"
    },
    {
     "alias": "Output-ES",
     "dimensions": {
      "component_id": "es_out_livelogs",
      "component_kind": "*",
      "component_name": "*",
      "component_type": "*",
      "host": "*",
      "pid": "*"
     },
     "metricName": "component_received_events_total",
     "metricQueryType": 1,
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "tppp_v1", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "component_sent_events_total", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "es_out_livelogs" }, "property": { "name": "component_id", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "sink" }, "property": { "name": "component_kind", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(component_sent_events_total) FROM tppp_v1 WHERE component_id = 'es_out_livelogs' AND component_kind = 'sink'",
     "statistic": "Sum"
    },
    { "expression": "$Input - $Output_ES", "type": "math" }
   ]
  },
  {
   "title": "Pattern Performance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "$inputPattern1 - $outputPattern1",
     "type": "math"
    },
    {
     "expression": "$inputPattern2 - $outputPattern2",
     "type": "math"
    },
    {
     "expression": "$inputPattern3 - $outputPattern3",
     "type": "math"
    },
    {
     "expression": "$inputPattern4 - $outputPattern4",
     "type": "math"
    },
    {
     "expression": "$inputPattern5 - $outputPattern5",
     "type": "math"
    },
    {
     "expression": "$inputPattern6 - $outputPattern6",
     "type": "math"
    }
   ]
  },
  { "title": "Pipeline-Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Output Buffer Avg.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "Avg. ES-Buffer",
     "dimensions": {
      "buffer_type": "*",
      "component_id": "es_out_livelogs",
      "component_kind": "sink",
      "component_name": "*",
      "component_type": "*",
      "host": "*",
      "pid": "*",
      "stage": "*"
     },
     "metricName": "buffer_events",
     "metricQueryType": 1,
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "tppp_v1", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "buffer_events", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "es_out_livelogs" }, "property": { "name": "component_id", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "sink" }, "property": { "name": "component_kind", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "memory" }, "property": { "name": "buffer_type", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(buffer_events) FROM tppp_v1 WHERE component_id = 'es_out_livelogs' AND component_kind = 'sink' AND buffer_type = 'memory'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Output Buffers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "dimensions": {
      "buffer_type": "*",
      "component_id": "es_out_livelogs",
      "component_kind": "sink",
      "component_name": "*",
      "component_type": "*",
      "host": "*",
      "pid": "*",
      "stage": "*"
     },
     "metricName": "buffer_events",
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Kafka SumOffsetLag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SumOffsetLag",
     "dimensions": { "Cluster Name": "logrelay-latest-v8", "Consumer Group": "livelogs-consumer", "Topic": "cdm-livelogs" },
     "metricName": "SumOffsetLag",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Resources-Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "# of Vector Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 2", "type": "math" },
    { "expression": "$Vector / 2", "type": "math" }
   ]
  },
  {
   "title": "Host CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 22 },
   "targets": [
    {
     "alias": "EKS-Cluster-Average-%",
     "dimensions": { "AutoScalingGroupName": "eks-tppp-dataplane-ng-01" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "collector": "cpu", "cpu": "*", "host": "*", "mode": "user" },
     "metricName": "cpu_seconds_total",
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Host Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 22 },
   "targets": [
    {
     "dimensions": { "collector": "memory", "host": "*" },
     "metricName": "memory_active_bytes",
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "collector": "memory", "host": "vector-tppp-dataplane-0" },
     "metricName": "memory_total_bytes",
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Host-Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "dimensions": { "collector": "network", "device": "eth0", "host": "*" },
     "metricName": "network_receive_bytes_total",
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "collector": "network", "device": "eth0", "host": "*" },
     "metricName": "network_transmit_bytes_total",
     "namespace": "tppp_v1",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}